apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    id: "929858"
    app: mariadb
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: "929858"
      app: mariadb
      env: dev
  template:
    metadata:
      labels:
        id: "929858"
        app: mariadb
        env: dev
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: MYSQL_DATABASE
          value: "{{ .Values.db.name }}"
        - name: MYSQL_USER
          value: "{{ .Values.db.user }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.db.password }}"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: {{ .Values.service.port }}
