apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  username: "{{ .Values.db.user }}"       # String value
  password: "{{ .Values.db.password }}"   # String value
  database: "{{ .Values.db.name }}"       # String value
