apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    id: "929858"
    app: mariadb
    env: dev
spec:
  selector:
    id: "929858"
    app: mariadb
    env: dev
  ports:
    - port: 3306
      targetPort: 3306
