apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    id: "929858"
    app: nginx
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: "929858"
      app: nginx
      env: dev
  template:
    metadata:
      labels:
        id: "929858"
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-config
