apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    id: 929858
    app: nginx
    env: dev
spec:
  type: NodePort
  selector:
    id: 929858
    app: nginx
    env: dev
  ports:
    - port: 80
      nodePort: 30080
      targetPort: 80
