apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    id: "929858"
    app: wordpress
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: "929858"
      app: wordpress
      env: dev
  template:
    metadata:
      labels:
        id: "929858"
        app: wordpress
        env: dev
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: WORDPRESS_DB_HOST
          value: "{{ .Values.wordpress.db_host }}"
        - name: WORDPRESS_DB_USER
          value: "{{ .Values.wordpress.db_user }}"
        - name: WORDPRESS_DB_PASSWORD
          value: "{{ .Values.wordpress.db_password }}"
        - name: WORDPRESS_DB_NAME
          value: "{{ .Values.wordpress.db_name }}"
        ports:
        - containerPort: {{ .Values.service.port }}
