apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    id: "929858"
    app: wordpress
    env: dev
spec:
  type: NodePort
  selector:
    id: "929858"
    app: wordpress
    env: dev
  ports:
    - port: 80
      targetPort: 80
